package:
  name: osdag_latex_env
  version: "1.0.0"

source:
  path: ..

build:
  number: 0
  noarch: false
  script:

    - {{ PYTHON }} -m pip install . --no-deps -vv

    # Windows
    - if not exist %PREFIX%\\Library\\bin mkdir %PREFIX%\\Library\\bin      # [win]
    - if not exist %PREFIX%\\Library\\share mkdir %PREFIX%\\Library\\share    # [win]
    - robocopy assets\\windows\\bin %PREFIX%\\Library\\bin /E || IF %ERRORLEVEL% GEQ 8 EXIT /B 1   # [win]
    - robocopy assets\\texmf %PREFIX%\\Library\\share /E || IF %ERRORLEVEL% GEQ 8 EXIT /B 1  # [win]

    # Linux
    - mkdir -p $PREFIX/share                # [linux]
    - cp -r ../assets/linux/bin/* $PREFIX/bin/         # [linux]
    - cp -r ../assets/texmf/* $PREFIX/share  # [linux]

    # macOS
    - mkdir -p $PREFIX/share                # [osx]
    - cp -r ../assets/macos/bin/* $PREFIX/bin/         # [osx]
    - cp -r ../assets/texmf/* $PREFIX/share  # [osx]

requirements:
  build:
    - python
    - setuptools
    - pip
  host:
    - setuptools
    - pip
    - python
  run:
    - python

about:
  summary: Self-contained cross-platform LaTeX toolchain for Osdag
  license: LGPL-3.0-only
  license_family: LGPL
  home: https://osdag.fossee.in
  dev_url: https://github.com/osdag-admin/osdag-latex-env
  doc_url: https://github.com/osdag-admin/osdag-latex-env
